### ISSUE TITLE
行方不明のDENSO QRリーダ(USB接続)を探す

### ISSUE THREAD

**Issue by jms-funato** [jms-web/JMS#28]
denso AT10q-sb

### 探した場所
- 3F非常口前の棚(念のため経理資料側の棚も確認)
- 会議室の機材入れ
- 2F机回り
- 1F作業部屋棚
- 1F倉庫部屋(旧掃除道具入れ)

### ありそうな場所
- 野呂さんが持っていっていないか
- 秋山さんのスペースに紛れていないか

**Comment by jms-arai** [comment]
船戸くんへ

鬼頭精器のテスト用に借用中です。
必要であれば返しに行きます。

**Comment by jms-funato** [comment]
@jms-arai さんへ
QRリーダですが、今すぐ必要というわけではないです。
必要そうな案件が出来たら連絡しますので、
そのときに返却して頂ければ結構です。
